---
language: generic

sudo: required

services:
  - docker

cache:
  directories:
    - .flatpak-builder

before_script:
  - git clone -b gh-pages https://github.com/$TRAVIS_REPO_SLUG export/ && cp -rf export/repo . || mkdir export

script:
  - docker run --privileged -v ${PWD}:/source -i vrutkovs/flatpak:latest make -C source/

before_deploy:
  - rm -rf export && mkdir export
  - cp -rf repo/ export/
  - cp -rf bat.flatpakref export/

deploy:
  provider: s3
  access_key_id: $MINIO_ACCESS_KEY
  secret_access_key: $MINIO_ACCESS_KEY
  bucket: flatpak
  local_dir: export
  upload-dir: bat
  endpoint: https://minio.vrutkovs.eu
  on:
    branch: minio
